### ISSUE TITLE
Binary Conversion

### ISSUE THREAD

**Issue by son4john** [son4john/VectorNav-SDK-Testing#12]
Hi, Alan I have something that i could use your help with when you get a chance. We need to create a binary to .txt converter. Basically it will read in any type of binary data and then covert it into txt. Think about what that will take. I will attach a sample binary file for you.

**Comment by joalen** [comment]
Okay, I believe I have a solution, although, it may not be perfect because some checks I've used are just patterns I've noticed when reading the output from terminal. 

For binary files, I found that looking through a hexadecimal viewer is easier for me to see what data I'm working with. From seeing the hexadecimal viewer, I'm certain it is VectorNav sensor data, which if I read the documentation right, is in ASCII format. 

For me to make the Binary To Text Converter, I first made a function that would output contents as a vector for easier storage. From there, I instantiated an ifstream object with the binary parameter to read the file in binary mode. Here are the steps I planned to make the binary file into a user-friendly format: 

1. From reading the hexadecimal version, I saw that there was malformed data (like line-feeders, invalid data, etc.) --> I removed those from the parsing stage by checking if those characters are valid and printable ASCII characters in a terminal. If pass, then that character moves on. Else, it fails. 
2. The next stage is preparing to turn that binary data into two-digit hexadecimal numbers. 
3. Hexadecimal --> Integer
4. Integer --> Char
5. Then, I noticed that there were unusual line-breaks, so I made a condition to assert that the text stream object will end and append to the parse vector. 

After handling parsing of binary to string, I then write to a text file that comes by creating an ofstream object and then looping through the parse vector and continuously write until end of vector. 

Here's the code I've written (it is a .zip file, which contains the code, its exe, output from running exe, and bin file): 
[Binary to Text Converter.zip](https://github.com/son4john/VectorNav-SDK-Testing/files/13538022/Binary.to.Text.Converter.zip)
