### ISSUE TITLE
Binary Conversion 2 - ASCII Message and Binary Message

### ISSUE THREAD

**Issue by son4john** [son4john/VectorNav-SDK-Testing#13]
I like the code it's a good first step.

Now I'm going to give you different logs to parse. Your program should be robust enough to parse all of them.
[logs.zip](https://github.com/son4john/VectorNav-SDK-Testing/files/13573033/logs.zip)

I would also try to rewrite the code without the namespace portion for example  std::cout << "Hello World!";

**Comment by joalen** [comment]
Hi! I just saw this and forgot this issue existed; I believe GitHub did not notify me about the new issue. Anyway, I revamped the original solution and realized a few things!

1. When I ran my original solution against log4.bin, it threw those weird, non-printable ASCII characters that translated to weird Unicode characters. I analyzed the file by running that .log file to the log viewer in the Control Center and found that there were two pieces of information: ASCII (otherwise known as the [NMEA 0183 standard](https://en.wikipedia.org/wiki/NMEA_0183)) and binary messages, which explains why the hex editor showed cases of data that were invalid; these were proprietary Binary messages that the sensor stores. 
2. Realizing this, I returned to the drawing board and edited the main method for reading and parsing the file contents. I removed a function that tried to remove any non-printable ASCII character and decided to iterate through all of them to grab bytes that started with "FA" and ended with "$." 
3. I then added C++ code that addressed reading and parsing these Binary messages, which started by iterating over the file, but it must stop when a "0x24" byte was detected. In other words, a "$" mark in ASCII. To get the "FA" byte, I had to check for the hexadecimal string equivalent of "fffffffa." It turns out that a deeper analysis of the binary file indicated more of these "F" bytes, which I had to make conditions to extract. 
4. From there, I "beautified" the binary message by making all the bytes with letters in uppercase format. 
5. I also wanted to address the issue of modularity within the program and did not feel like pushing the binary messages and ASCII messages in a single vector and making a huge file. Instead, I opted to make a custom struct data type that stores two types: ASCII measurements and binary measurements, both of which are string vectors.
6. Since the sensor uses the NMEA 0183 protocol, I learned that it starts with a "$" and ends on a carriage-return character ('\r')
7. Even if I translated all the ASCII messages to purge binary message bytes, a few managed to circumvent the filters, so I implemented a function that removes those non-printable ASCII characters and makes the file readable. 
8. I changed the `main()` function to now implement processes for giving either a single file or multiple files (for batch processing) and stop method calls to the binary measurement function that has no binary measurement data to read. 

Here is the .zip file containing the code and the parsed bin files. Note that I've tested both the batch-processing and single-file processing methods. Here are the results!

[Updated Binary to Text Converter.zip](https://github.com/son4john/VectorNav-SDK-Testing/files/13934287/Updated.Binary.to.Text.Converter.zip)
